/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "Ativo"
 * 	found in "../Ativo.asn1"
 */

#ifndef	_Tipo1_H_
#define	_Tipo1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IntList.h"
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Tipo1 */
typedef struct Tipo1 {
	IntList_t	 id;
	PrintableString_t	 nome;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Tipo1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Tipo1;

#ifdef __cplusplus
}
#endif

#endif	/* _Tipo1_H_ */
#include <asn_internal.h>
