/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "Ativo"
 * 	found in "../Ativo.asn1"
 */

#ifndef	_Tipo2_H_
#define	_Tipo2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BoolList.h"
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Tipo2 */
typedef struct Tipo2 {
	BoolList_t	 id;
	PrintableString_t	 nome;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Tipo2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Tipo2;

#ifdef __cplusplus
}
#endif

#endif	/* _Tipo2_H_ */
#include <asn_internal.h>
